const currencies = [
    { code: 'USD', name: 'US Dollar', country: 'US' },
    { code: 'EUR', name: 'Euro', country: 'EU' },
    { code: 'JPY', name: 'Japanese Yen', country: 'JP' },
    { code: 'GBP', name: 'British Pound', country: 'GB' },
    { code: 'AUD', name: 'Australian Dollar', country: 'AU' },
    { code: 'CAD', name: 'Canadian Dollar', country: 'CA' },
    { code: 'CHF', name: 'Swiss Franc', country: 'CH' },
    { code: 'CNY', name: 'Chinese Yuan', country: 'CN' },
    { code: 'SEK', name: 'Swedish Krona', country: 'SE' },
    { code: 'NZD', name: 'New Zealand Dollar', country: 'NZ' },
    { code: 'MXN', name: 'Mexican Peso', country: 'MX' },
    { code: 'SGD', name: 'Singapore Dollar', country: 'SG' },
    { code: 'HKD', name: 'Hong Kong Dollar', country: 'HK' },
    { code: 'NOK', name: 'Norwegian Krone', country: 'NO' },
    { code: 'KRW', name: 'South Korean Won', country: 'KR' },
    { code: 'TRY', name: 'Turkish Lira', country: 'TR' },
    { code: 'RUB', name: 'Russian Ruble', country: 'RU' },
    { code: 'INR', name: 'Indian Rupee', country: 'IN' },
    { code: 'BRL', name: 'Brazilian Real', country: 'BR' },
    { code: 'ZAR', name: 'South African Rand', country: 'ZA' },
    { code: 'AED', name: 'United Arab Emirates Dirham', country: 'AE' },
    { code: 'ARS', name: 'Argentine Peso', country: 'AR' },
    { code: 'CLP', name: 'Chilean Peso', country: 'CL' },
    { code: 'COP', name: 'Colombian Peso', country: 'CO' },
    { code: 'PEN', name: 'Peruvian Nuevo Sol', country: 'PE' },
    { code: 'VND', name: 'Vietnamese Dong', country: 'VN' },
    { code: 'MYR', name: 'Malaysian Ringgit', country: 'MY' },
    { code: 'THB', name: 'Thai Baht', country: 'TH' },
    { code: 'PHP', name: 'Philippine Peso', country: 'PH' },
    { code: 'TWD', name: 'New Taiwan Dollar', country: 'TW' },
    { code: 'PKR', name: 'Pakistani Rupee', country: 'PK' },
    { code: 'IDR', name: 'Indonesian Rupiah', country: 'ID' },
    { code: 'BHD', name: 'Bahraini Dinar', country: 'BH' },
    { code: 'KWD', name: 'Kuwaiti Dinar', country: 'KW' },
    { code: 'OMR', name: 'Omani Rial', country: 'OM' },
    { code: 'QAR', name: 'Qatari Rial', country: 'QA' },
    { code: 'JOD', name: 'Jordanian Dinar', country: 'JO' },
    { code: 'LKR', name: 'Sri Lankan Rupee', country: 'LK' },
    { code: 'BGN', name: 'Bulgarian Lev', country: 'BG' },
    { code: 'HRK', name: 'Croatian Kuna', country: 'HR' },
    { code: 'CZK', name: 'Czech Koruna', country: 'CZ' },
    { code: 'HUF', name: 'Hungarian Forint', country: 'HU' },
    { code: 'ISK', name: 'Icelandic Króna', country: 'IS' },
    { code: 'RON', name: 'Romanian Leu', country: 'RO' },
    { code: 'SAR', name: 'Saudi Riyal', country: 'SA' },
    { code: 'NPR', name: 'Nepalese Rupee', country: 'NP' },
    { code: 'MOP', name: 'Macanese Pataca', country: 'MO' },
    { code: 'MAD', name: 'Moroccan Dirham', country: 'MA' },
    { code: 'DZD', name: 'Algerian Dinar', country: 'DZ' },
    { code: 'TND', name: 'Tunisian Dinar', country: 'TN' },
    { code: 'SDG', name: 'Sudanese Pound', country: 'SD' },
    { code: 'ETB', name: 'Ethiopian Birr', country: 'ET' },
    { code: 'GHS', name: 'Ghanaian Cedi', country: 'GH' },
    { code: 'KES', name: 'Kenyan Shilling', country: 'KE' },
    { code: 'TZS', name: 'Tanzanian Shilling', country: 'TZ' },
    { code: 'UGX', name: 'Ugandan Shilling', country: 'UG' },
    { code: 'XOF', name: 'West African CFA Franc', country: 'CI' },
    { code: 'XAF', name: 'Central African CFA Franc', country: 'CM' },
    { code: 'MZN', name: 'Mozambican Metical', country: 'MZ' },
    { code: 'NAD', name: 'Namibian Dollar', country: 'NA' },
    { code: 'AWG', name: 'Aruban Florin', country: 'AW' },
    { code: 'ANG', name: 'Netherlands Antillean Guilder', country: 'CW' },
    { code: 'SVC', name: 'Salvadoran Colón', country: 'SV' },
    { code: 'CUP', name: 'Cuban Peso', country: 'CU' },
    { code: 'CUC', name: 'Cuban Convertible Peso', country: 'CU' },
    { code: 'FJD', name: 'Fijian Dollar', country: 'FJ' },
    { code: 'PGK', name: 'Papua New Guinean Kina', country: 'PG' },
    { code: 'BBD', name: 'Barbadian Dollar', country: 'BB' },
    { code: 'BMD', name: 'Bermudian Dollar', country: 'BM' },
    { code: 'SRD', name: 'Surinamese Dollar', country: 'SR' },
    { code: 'BND', name: 'Brunei Dollar', country: 'BN' },
    { code: 'DOP', name: 'Dominican Peso', country: 'DO' },
    { code: 'CNY', name: 'Chinese Yuan Renminbi', country: 'CN' },
    { code: 'LBP', name: 'Lebanese Pound', country: 'LB' },
    { code: 'BIF', name: 'Burundian Franc', country: 'BI' },
    { code: 'RWF', name: 'Rwandan Franc', country: 'RW' },
    { code: 'SLL', name: 'Sierra Leonean Leone', country: 'SL' },
    { code: 'DJF', name: 'Djiboutian Franc', country: 'DJ' },
    { code: 'MRU', name: 'Mauritanian Ouguiya', country: 'MR' },
    { code: 'GMD', name: 'Gambian Dalasi', country: 'GM' },
    { code: 'MGA', name: 'Malagasy Ariary', country: 'MG' },
    { code: 'SCR', name: 'Seychellois Rupee', country: 'SC' },
    { code: 'XPF', name: 'CFP Franc', country: 'PF' },
    { code: 'BWP', name: 'Botswana Pula', country: 'BW' },
    { code: 'KZT', name: 'Kazakhstani Tenge', country: 'KZ' },
    { code: 'AZN', name: 'Azerbaijani Manat', country: 'AZ' },
    { code: 'TJS', name: 'Tajikistani Somoni', country: 'TJ' },
    { code: 'MDL', name: 'Moldovan Leu', country: 'MD' },
    { code: 'LYD', name: 'Libyan Dinar', country: 'LY' },
    { code: 'TMT', name: 'Turkmenistani Manat', country: 'TM' },
    { code: 'GEL', name: 'Georgian Lari', country: 'GE' },
    { code: 'NOK', name: 'Norwegian Krone', country: 'NO' },
  ];
  
  export default currencies;
  